language: java

before_install:
  - sudo apt-get update
  - sudo apt-get install -y node

script: ./b clean && ./b build check

sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.npm

